for i in selection do 
(
    posc = i.pos.controller 
    rotc = i.rotation.controller
    sclc = i.scale.controller 

    isPosScript = iskindof posc position_script
    if isPosScript == true do 
    (
        posScript = posc.script 
        posVari = posc.NumVariables()
        for i=5 to posVari do 
        (
            
        )
    )
    if rotc == rotation_script do 
    (

    )
    if sclc == scale_script do 
    (

    )
)

